from deepmd_jax.train import train

# training an energy-force model
train(
      model_type='energy',              # Model type
      rcut=6.0,                              # Cutoff radius
      save_path='model.pkl',  # Path to save the trained model
      progress_path='progress.out',  # Path to save the training progress
      train_data_path=[
        "../../training-data/ab-initio/MB-pol/00_dlpoly_198K",
        "../../training-data/ab-initio/MB-pol/00_dlpoly_208K",
        "../../training-data/ab-initio/MB-pol/00_dlpoly_213K",
        "../../training-data/ab-initio/MB-pol/00_dlpoly_218K",
        "../../training-data/ab-initio/MB-pol/00_dlpoly_223K",
        "../../training-data/ab-initio/MB-pol/00_dlpoly_228K",
        "../../training-data/ab-initio/MB-pol/00_dlpoly_238K",
        "../../training-data/ab-initio/MB-pol/00_dlpoly_248K",
        "../../training-data/ab-initio/MB-pol/00_dlpoly_258K",
        "../../training-data/ab-initio/MB-pol/00_dlpoly_268K",
        "../../training-data/ab-initio/MB-pol/00_dlpoly_278K",
        "../../training-data/ab-initio/MB-pol/00_dlpoly_288K",
        "../../training-data/ab-initio/MB-pol/00_dlpoly_298K",
        "../../training-data/ab-initio/MB-pol/00_dlpoly_308K",
        "../../training-data/ab-initio/MB-pol/00_dlpoly_318K",
        "../../training-data/ab-initio/MB-pol/00_dlpoly_328K",
        "../../training-data/ab-initio/MB-pol/00_dlpoly_338K",
        "../../training-data/ab-initio/MB-pol/00_dlpoly_348K",
        "../../training-data/ab-initio/MB-pol/00_dlpoly_368K",
        "../../training-data/ab-initio/MB-pol/01_MB-polRefLiquidHighPressure_198K",
        "../../training-data/ab-initio/MB-pol/01_MB-polRefLiquidHighPressure_203K",
        "../../training-data/ab-initio/MB-pol/01_MB-polRefLiquidHighPressure_208K",
        "../../training-data/ab-initio/MB-pol/01_MB-polRefLiquidHighPressure_213K",
        "../../training-data/ab-initio/MB-pol/01_MB-polRefLiquidHighPressure_218K",
        "../../training-data/ab-initio/MB-pol/01_MB-polRefLiquidHighPressure_223K",
        "../../training-data/ab-initio/MB-pol/01_MB-polRefLiquidHighPressure_228K",
        "../../training-data/ab-initio/MB-pol/01_MB-polRefLiquidHighPressure_238K",
        "../../training-data/ab-initio/MB-pol/01_MB-polRefLiquidHighPressure_268K",
        "../../training-data/ab-initio/MB-pol/01_MB-polRefLiquidHighPressure_298K",
        "../../training-data/ab-initio/MB-pol/05_DPUnstable_198K",
        "../../training-data/ab-initio/MB-pol/05_DPUnstable_208K",
        "../../training-data/ab-initio/MB-pol/05_DPUnstable_213K",
        "../../training-data/ab-initio/MB-pol/05_DPUnstable_218K",
        "../../training-data/ab-initio/MB-pol/05_DPUnstable_223K",
        "../../training-data/ab-initio/MB-pol/05_DPUnstable_228K",
        "../../training-data/ab-initio/MB-pol/05_DPUnstable_238K",
        "../../training-data/ab-initio/MB-pol/05_DPUnstable_248K",
        "../../training-data/ab-initio/MB-pol/05_DPUnstable_258K",
        "../../training-data/ab-initio/MB-pol/05_DPUnstable_268K",
        "../../training-data/ab-initio/MB-pol/05_DPUnstable_278K",
        "../../training-data/ab-initio/MB-pol/05_DPUnstable_288K",
        "../../training-data/ab-initio/MB-pol/05_DPUnstable_298K",
        "../../training-data/ab-initio/MB-pol/05_DPUnstable_308K",
        "../../training-data/ab-initio/MB-pol/05_DPUnstable_318K",
        "../../training-data/ab-initio/MB-pol/05_DPUnstable_328K",
        "../../training-data/ab-initio/MB-pol/05_DPUnstable_338K",
        "../../training-data/ab-initio/MB-pol/05_DPUnstable_348K",
        "../../training-data/ab-initio/MB-pol/05_DPUnstable_368K",
        "../../training-data/ab-initio/MB-pol/05_DPUnstable_500K",
        "../../training-data/ab-initio/MB-pol/06_DPLessAcc_288K",
        "../../training-data/ab-initio/MB-pol/06_DPLessAcc_298K",
        "../../training-data/ab-initio/MB-pol/06_DPLessAcc_308K",
        "../../training-data/ab-initio/MB-pol/06_DPLessAcc_318K",
        "../../training-data/ab-initio/MB-pol/06_DPLessAcc_328K",
        "../../training-data/ab-initio/MB-pol/06_DPLessAcc_338K",
        # "../../training-data/ab-initio/MB-pol/10_MB-polRefOrthogonalIce_Ice_III",
        # "../../training-data/ab-initio/MB-pol/10_MB-polRefOrthogonalIce_Ice_IX",
        # "../../training-data/ab-initio/MB-pol/10_MB-polRefOrthogonalIce_Ice_Ic",
        # "../../training-data/ab-initio/MB-pol/10_MB-polRefOrthogonalIce_Ice_Ih",
        # "../../training-data/ab-initio/MB-pol/10_MB-polRefOrthogonalIce_Ice_SIII",
        # "../../training-data/ab-initio/MB-pol/10_MB-polRefOrthogonalIce_Ice_VI",
        # "../../training-data/ab-initio/MB-pol/10_MB-polRefOrthogonalIce_Ice_VII",
        # "../../training-data/ab-initio/MB-pol/10_MB-polRefOrthogonalIce_Ice_VIII",
        # "../../training-data/ab-initio/MB-pol/10_MB-polRefOrthogonalIce_Ice_XI",
        # "../../training-data/ab-initio/MB-pol/10_MB-polRefOrthogonalIce_Ice_XII",
        # "../../training-data/ab-initio/MB-pol/10_MB-polRefOrthogonalIce_Ice_XVI",
        # "../../training-data/ab-initio/MB-pol/10_MB-polRefOrthogonalIce_Ice_XVII",
        # "../../training-data/ab-initio/MB-pol/10_MB-polRefTriclinicIce_Ice_II",
        # "../../training-data/ab-initio/MB-pol/10_MB-polRefTriclinicIce_Ice_IV",
        # "../../training-data/ab-initio/MB-pol/10_MB-polRefTriclinicIce_Ice_V",
        # "../../training-data/ab-initio/MB-pol/10_MB-polRefTriclinicIce_Ice_XIII",
        # "../../training-data/ab-initio/MB-pol/10_MB-polRefTriclinicIce_Ice_XIV",
        # "../../training-data/ab-initio/MB-pol/10_MB-polRefTriclinicIce_Ice_XV",
        # "../../training-data/ab-initio/MB-pol/15_IceIII_Liquid",
        # "../../training-data/ab-initio/MB-pol/15_IceII_Liquid",
        # "../../training-data/ab-initio/MB-pol/15_IceIh_Liquid",
        # "../../training-data/ab-initio/MB-pol/15_IceV_Liquid",
        # "../../training-data/ab-initio/MB-pol/15_Ice_II",
        # "../../training-data/ab-initio/MB-pol/15_Ice_III",
        # "../../training-data/ab-initio/MB-pol/15_Ice_IV",
        # "../../training-data/ab-initio/MB-pol/15_Ice_IX",
        # "../../training-data/ab-initio/MB-pol/15_Ice_Ic",
        # "../../training-data/ab-initio/MB-pol/15_Ice_Ih",
        # "../../training-data/ab-initio/MB-pol/15_Ice_SIII",
        # "../../training-data/ab-initio/MB-pol/15_Ice_V",
        # "../../training-data/ab-initio/MB-pol/15_Ice_VI",
        # "../../training-data/ab-initio/MB-pol/15_Ice_VII",
        # "../../training-data/ab-initio/MB-pol/15_Ice_VIII",
        # "../../training-data/ab-initio/MB-pol/15_Ice_XI",
        # "../../training-data/ab-initio/MB-pol/15_Ice_XII",
        # "../../training-data/ab-initio/MB-pol/15_Ice_XIII",
        # "../../training-data/ab-initio/MB-pol/15_Ice_XIV",
        # "../../training-data/ab-initio/MB-pol/15_Ice_XV",
        # "../../training-data/ab-initio/MB-pol/15_Ice_XVI",
        # "../../training-data/ab-initio/MB-pol/15_Ice_XVII"
      ], # Path (or a list of paths) to the training dataset
      step=1000000,                          # Number of training steps
      print_every = 1,
)
